<html>
<head>
    <meta charset="utf-8">
          <title> Laura Bernadete Vieira </title>
    <link rel="stylesheet" href="HTML%20treta.css">
    </head>
    
    
<body>


<table border="0">
<tr>
<td><h1><strong><font color="blue">Laura Bernadete Vieira</font></strong></h1>
<h3>Solteira, Brasileira, 25 anos,
Rua João Lisboa, 63 – Pilares - Rio de Janeiro 

Contatos: vieirablaura@gmail.com
    cel: 21 9.9555 9915
    </h3></div>

</td>
<td align="right"><figure id="foto">
       <img src="laura1.png" >
    </figure></td> </td>
</tr>
<tr>
<td colspan=2>
<div class="h3">
    
	
    <h2>Formação Acadêmica</h2>
    <h4><strong><em>Nível superior</em></strong> Psicologia - IBMR – Instituto Brasileiro de Medicina e Reabilitação | Concluído 12/2016</h4>
    <h2>Experiência profissional</h2>
    <h5> <p>Randstad - Analista de RH - Junho/2014 (Atual)
Atuo na triagem de currículos, seleção de candidatos de forma individual e em grupo, aplicação de testes (Quati, Palográfico, BFP e AC) contato com o cliente, preparação de perfil de vagas, prospecção de vagas e novos clientes, visitas de relacionamento.
Projeto Olimpíadas - Avaliação de 700 profissionais bilíngues, processo de admissão e demissão a nível Brasil e administração 1200 agentes de bilheteria e coordenadores.
Projeto Heineken – Restruturação da equipe de promotores de vendas.
Projeto Lacta – Avaliação e contratação de 260 animadores de páscoa do Rio de Janeiro e regiões.</p>

<p>IBMR – Estagiária de Orientação Vocacional - Janeiro/2015 á Dezembro/2016
Atendimento á adultos e adolescentes que estão decidindo seu futuro profissional. Através de pesquisas, análise de provas de interesses, aptidões e personalidade, algumas orientações sobre o percurso acadêmico e profissional indicado, bem como estratégias de autoconhecimento e pesquisa. Testes: G36, R1, AIP, TDP, HTTP entre outros, questionários e demais observações.</p>

<p>Kelly Services consultoria – Estagiaria de RH – Novembro/2013 á Julho/2014
Atividades: Suporte a atendimento de candidatos, recrutamento, suporte na aplicação de testes (Palográfico, Quati, AC, G36). No DP recolhi documentação, gerando rescisões e auxiliando em outros procedimentos.</p>

<p>Ammarhes Consultoria em Medicina e Segurança do Trabalho - Assistente Técnico em Segurança do Trabalho – Maio a Set/ 2012 - Contrato Temporário.
Atividades: Elaboração de documentos (PPRA, LTCAT, laudo ergonômico, laudo de insalubridade, entre outros) de diversas empresas do Rio de Janeiro e São Paulo, treinamentos (CIPA, altura,etc); Parte comercial, elaboração de propostas comerciais e visitas á clientes.</p>

<p>Telefônica Vivo - Estagiária em Segurança do Trabalho - Maio/2011 a Maio/2012 Atividades: Investigação, elaboração e abertura de CAT, inspeções de segurança, análise de documentação, treinamentos, elaboração de relatórios, reuniões (CIPA, periódicas,...), organização de SIPAT.</p>
</h5>
 
</td>
</tr>

</table>

    </body>
